### ISSUE TITLE
skip links question

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio-new#1]
Hi @thomasjbradley, 

My skip links focus state (see main/css and .skip-links a:focus) is not working. It appeared before my styling, but after I added the focus state it does not appear when tabbing through site? I added a red background and white outline but still can't see it. Can you see where I went wrong? :/

Thanks!

Viv

**Comment by thomasjbradley** [comment]
They're working fine, but they're hidden behind the banner or the navigation. Try adding `z-index` onto the skip link a tags.

**Comment by vivkay** [comment]
YES! Thank you!
