### ISSUE TITLE
Image flex

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio-new#3]
Hi @thomasjbradley, 

I'm stumped on something that should be basic – I've been using so many background images I've forgotten how to make a full image responsive.

I tried putting a width of 100% and height of auto. I tried display as cover and overflow hidden. But either I get a squished image that's full-width (if it's not in a unit) or an image that stays proportional but doesn't stay full-width larger screens (it cuts off half way, but only after the large screen size).

What am I missing?

Thanks!

V
![screen shot 2015-10-31 at 5 11 57 pm](https://cloud.githubusercontent.com/assets/6340292/10865910/86f4b2fa-7ff2-11e5-8cea-f1685c8044fa.png)
![screen shot 2015-10-31 at 5 11 33 pm](https://cloud.githubusercontent.com/assets/6340292/10865912/880724fc-7ff2-11e5-8bc4-33f5fb20ef5f.png)

```
    <div class="grid">
        <div class="unit unit-xs-1 unit-s-1 unit-m-1 unit-l-1 unit-xl-1 full-bleed">
            <img class="full-bleed" src="{{baseurl}}/img/{{page.img-3}}">
        </div>
    </div>
```

**Comment by vivkay** [comment]
CSS:

```
.full-bleed {
    width: 100%;
    height: auto;  
}

```

**Comment by thomasjbradley** [comment]
That class makes sense, I'd add `display: block` to it also.
But it shouldn't be on the `<div class="unit">` only on the `<img>`.

**Comment by vivkay** [comment]
I just added display as block and it didn't seem to change. I took it off the div class too. :/

**Comment by vivkay** [comment]
It behaces the same way with this code

```
    <div class="grid">
        <div class="unit unit-xs-1">
            <img class="full-bleed" src="{{ baseurl }}/img/{{ page.img-4 }}" alt="{{ page.img-4-alt }}">
        </div>
    </div>
```

**Comment by vivkay** [comment]
I just updated it on Github so you can see. It's funky!!

**Comment by vivkay** [comment]
(but surprisingly perfect at the smaller sizes. It is full-width and responds wonderfully). I suspect it's something small that I'm just not seeing…

**Comment by thomasjbradley** [comment]
What page can I see it on?

**Comment by vivkay** [comment]
well… this one: http://vivkay.github.io/portfolio-new/explouria/

but I noticed that while it's showing on my local-host, the images aren't showing on this page

**Comment by vivkay** [comment]
I'm linking to them with the baseurl tags so I don't understand

**Comment by vivkay** [comment]
It's not a big problem – I can just leave the images a bit wonky. Could I come to your office hours on Tuesday instead? :dancer:

**Comment by thomasjbradley** [comment]
There seems to be some `<div class="grid">` tags unclosed.

I think there should be a closing `</div>` tag right here:
https://github.com/vivkay/portfolio-new/blob/gh-pages/_layouts/case-study-a.html#L20

And here:
https://github.com/vivkay/portfolio-new/blob/gh-pages/_layouts/case-study-a.html#L47

And here:
https://github.com/vivkay/portfolio-new/blob/gh-pages/_layouts/case-study-a.html#L56

**Comment by vivkay** [comment]
oh. my. goodness. I am so embarrassed. That was some sloppy indentation – it's because I've been moving things around all day, but no excuses! I will take more care. 

(yes that fixed it)

**Comment by vivkay** [comment]
The images still aren't showing up on github though, and I'm calling them like this:

```
    <div class="grid">
        <div class="unit unit-xs-1">
            <img class="full-bleed" src="{{ baseurl }}/img/{{ page.img-4 }}" alt="{{ page.img-4-alt }}">
        </div>
    </div>
```

But we can leave that for Tuesday!

**Comment by thomasjbradley** [comment]
`{{site.baseurl}}` — it's missing the `site.` part.

**Comment by vivkay** [comment]
OH. MY! Close though…I was close! ;)

**Comment by vivkay** [comment]
(it works. You are a genius and a saint @thomasjbradley )
