### ISSUE TITLE
html validator

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio-new#4]
Hi @thomasjbradley, 

I have a few questions about the warnings popping up from my HTML validator check. 

1. Do I need to follow the 'warnings'? There are some that say the role tags on the header, nav, main and footer are not necessary. But I thought these were for accessibility?

2. It's having an issue with the quotation marks in this line of code from my default.html file. I'm not sure how to fix it…all quotes look closed to me?

code:

```
<header class="hero" role="banner" {% if page.hero %}style="background-image: url({{site.baseurl}}/img/{{page.hero}}){% endif %}">
```

![screen shot 2015-11-16 at 9 37 20 pm](https://cloud.githubusercontent.com/assets/6340292/11201229/3f4168e4-8caa-11e5-8cbb-1d91de9eceb4.png)

**Comment by thomasjbradley** [comment]
*1.*

Yeah, ignore that `role` warning because some browsers support the roles and not the HTML elements themselves.

---

*2.*

The closing quotation mark, at the end of the line, should be inside the `{% endif %}`.

**Comment by vivkay** [comment]
sweet! thank you!!
