### ISSUE TITLE
media queries

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio-new#5]
Hi @thomasjbradley, 

This might be an in-person question, but let's see… 

So in my browser and on my iPad my website works nicely in two columns. I have set my mobile media query (size 'small') to single column. This previews great in my browser when I am at a small size (mimicking mobile), but on my iPhone 6 it still shows in two columns. Is this because the iPhone 6 has a larger resolution (or some technical thing that makes the website think that the screen is bigger than it is?) 

Let me know if I should pop by your office hours with my phone and I'll close the issue and see you tomorrow (Tuesday) at 2:30pm.

Thanks!!

**Comment by thomasjbradley** [comment]
It's because the `viewport` tag at the top of the default.html file isn't correct:
https://github.com/vivkay/portfolio-new/blob/gh-pages/_layouts/default.html#L6

It doesn't have viewport information in it, it looks like it has `<meta description>` information in it.

**Comment by vivkay** [comment]
THANK YOU!
